services:
  backend:
    container_name: kpd-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: kpd-backend
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - backend

  frontend:
    container_name: kpd-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kpd-frontend
    ports:
      - 5000:5000
    networks:
      - frontend

  postgres:
    restart: always
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/data/postgres/
    env_file:
      - .env
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend: